# Generated by Django 4.1.1 on 2022-09-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=12)),
                ('experience', models.CharField(max_length=15)),
                ('skills', models.CharField(max_length=80)),
                ('status', models.IntegerField(choices=[(0, 'Applied'), (1, 'Accepted'), (2, 'REJECTED')], default=0)),
            ],
        ),
    ]
