# Generated by Django 4.1.1 on 2022-09-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.URLField(default='file:///D:/Django/JobReviewApp/backend/api/dummy.txt', max_length=80),
        ),
    ]
