# Generated by Django 4.1.1 on 2022-09-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.URLField(default='https://itscr1spy.github.io/React-Portfolio-Website/', max_length=100),
        ),
    ]
