# Generated by Django 4.1.1 on 2022-09-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.ImageField(upload_to='resume/% Y/% m/% d/'),
        ),
    ]
