# Generated by Django 4.1.1 on 2022-09-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_candidate_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='details',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce turpis ligula, accumsan vitae elit vel, maximus egestas lorem. Mauris vel felis nunc. Praesent tortor ligula, tincidunt a sagittis fusce.', max_length=200),
        ),
    ]
