# Generated by Django 4.1.1 on 2022-09-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_candidate_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='details',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.URLField(default='https://itscr1spy.github.io/React-Portfolio-Website/', max_length=100),
        ),
    ]
